In [59]:
import pandas as pd
from pathlib import Path

In [60]:
from pathlib import Path

DATA_PATH = Path(r"C:\Users\Nithya Ganesh\Documents\clinical-trial-ai-assistant\data\raw")

print(DATA_PATH.exists())

True

In [61]:
trials = pd.read_csv(DATA_PATH / "trials.csv")

patients = pd.read_csv(DATA_PATH / "patients.csv")

sites = pd.read_csv(DATA_PATH / "sites.csv")

visits = pd.read_csv(DATA_PATH / "visits.csv")

adverse_events = pd.read_csv(DATA_PATH / "adverse_events.csv")

protocol_deviations = pd.read_csv(DATA_PATH / "protocol_deviations.csv")

drug_inventory = pd.read_csv(DATA_PATH / "drug_inventory.csv")

drug_shipments = pd.read_csv(DATA_PATH / "drug_shipments.csv")

lab_results = pd.read_csv(DATA_PATH / "lab_results.csv")

reference_codes = pd.read_csv(DATA_PATH / "reference_codes.csv")

In [62]:
trials.head()

,trial_id,phase,therapeutic_area,sponsor,study_drug,indication,start_date,planned_end_date,trial_status,target_enrollment
0,CT-ONC-001,Phase 2,Oncology,NovaCure Pharma,Drug A,Breast Cancer,2025-01-15,2026-06-30,Active,300
1,CT-CARD-002,Phase 3,Cardiology,MediCore Labs,Drug B,Heart Failure,2025-03-01,2026-12-15,Active,500
2,CT-DIAB-003,Phase 2,Endocrinology,HealthGen Bio,Drug C,Type 2 Diabetes,2024-11-20,2026-04-30,Active,250
3,CT-NEUR-004,Phase 1,Neurology,NeuroNova,Drug D,Migraine,2025-06-10,2026-08-31,Recruiting,120

In [63]:
trials.shape #helps to check the number of rows and columns in the dataframe

(4, 10)

In [64]:
trials.columns

Index(['trial_id', 'phase', 'therapeutic_area', 'sponsor', 'study_drug',
       'indication', 'start_date', 'planned_end_date', 'trial_status',
       'target_enrollment'],
      dtype='str')

In [65]:
trials.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   trial_id           4 non-null      str
 1   phase              4 non-null      str
 2   therapeutic_area   4 non-null      str
 3   sponsor            4 non-null      str
 4   study_drug         4 non-null      str
 5   indication         4 non-null      str
 6   start_date         4 non-null      str
 7   planned_end_date   4 non-null      str
 8   trial_status       4 non-null      str
 9   target_enrollment  4 non-null      int64
dtypes: int64(1), str(9)
memory usage: 794.0 bytes

In [66]:
trials.isnull().sum()

trial_id             0
phase                0
therapeutic_area     0
sponsor              0
study_drug           0
indication           0
start_date           0
planned_end_date     0
trial_status         0
target_enrollment    0
dtype: int64

In [67]:
trials.duplicated().sum()

np.int64(0)

In [68]:
trials.dtypes #to check the data type of columns

trial_id               str
phase                  str
therapeutic_area       str
sponsor                str
study_drug             str
indication             str
start_date             str
planned_end_date       str
trial_status           str
target_enrollment    int64
dtype: object

In [69]:
len(trials)

4

In [70]:
trials["trial_id"].nunique()  #if len(trials) and this equal then there is no duplicate values

4

In [71]:
patients.head()

,patient_id,trial_id,site_id,gender,age,consent_date,treatment_arm,enrollment_status
0,P00001,CT-ONC-001,SITE-001,Male,60,2025-04-12,Drug A,Enrolled
1,P00002,CT-ONC-001,SITE-001,Male,52,2025-07-06,Placebo,Enrolled
2,P00003,CT-ONC-001,SITE-001,Female,35,2025-02-18,Placebo,Screen Failed
3,P00004,CT-ONC-001,SITE-001,Male,32,2025-07-02,Placebo,Enrolled
4,P00005,CT-ONC-001,SITE-001,Female,35,2025-08-02,Placebo,Enrolled

In [72]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         318 non-null    str
 1   trial_id           317 non-null    str
 2   site_id            318 non-null    str
 3   gender             318 non-null    str
 4   age                318 non-null    int64
 5   consent_date       318 non-null    str
 6   treatment_arm      318 non-null    str
 7   enrollment_status  318 non-null    str
dtypes: int64(1), str(7)
memory usage: 37.2 KB

In [73]:
patients.shape

(318, 8)

In [74]:
patients.columns

Index(['patient_id', 'trial_id', 'site_id', 'gender', 'age', 'consent_date',
       'treatment_arm', 'enrollment_status'],
      dtype='str')

In [75]:
patients.isnull().sum()

patient_id           0
trial_id             1
site_id              0
gender               0
age                  0
consent_date         0
treatment_arm        0
enrollment_status    0
dtype: int64

In [76]:
patients.duplicated().sum()

np.int64(0)

In [77]:
sites.head()

,site_id,trial_id,site_name,country,country_code,principal_investigator,activation_date,site_status
0,SITE-001,CT-ONC-001,Hospital 1,India,IND,Investigator 1,2025-01-07,Pending
1,SITE-002,CT-ONC-001,Hospital 2,United States,USA,Investigator 2,2025-02-27,Activated
2,SITE-003,CT-ONC-001,Hospital 3,India,IND,Investigator 3,2025-06-23,Activated
3,SITE-004,CT-ONC-001,Hospital 4,Canada,CAN,Investigator 4,2025-04-19,Activated
4,SITE-005,CT-ONC-001,Hospital 5,India,IND,Investigator 5,2025-01-24,Activated

In [78]:
sites.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   site_id                 20 non-null     str
 1   trial_id                20 non-null     str
 2   site_name               20 non-null     str
 3   country                 20 non-null     str
 4   country_code            20 non-null     str
 5   principal_investigator  20 non-null     str
 6   activation_date         20 non-null     str
 7   site_status             20 non-null     str
dtypes: str(8)
memory usage: 2.8 KB

In [79]:
sites.shape

(20, 8)

In [80]:
sites.columns

Index(['site_id', 'trial_id', 'site_name', 'country', 'country_code',
       'principal_investigator', 'activation_date', 'site_status'],
      dtype='str')

In [81]:
sites.isnull().sum()

site_id                   0
trial_id                  0
site_name                 0
country                   0
country_code              0
principal_investigator    0
activation_date           0
site_status               0
dtype: int64

In [82]:
sites.duplicated().sum()

np.int64(0)

In [83]:
visits.head()

,visit_id,patient_id,trial_id,site_id,visit_name,visit_sequence,scheduled_visit_date,actual_visit_date,visit_status
0,V000001,P00001,CT-ONC-001,SITE-001,Screening,1,2025-04-12,NaN,Missed
1,V000002,P00001,CT-ONC-001,SITE-001,Baseline,2,2025-04-19,2025-04-17,Completed
2,V000003,P00001,CT-ONC-001,SITE-001,Week 4,3,2025-05-10,2025-05-13,Completed
3,V000004,P00001,CT-ONC-001,SITE-001,Week 8,4,2025-06-07,2025-06-09,Completed
4,V000005,P00001,CT-ONC-001,SITE-001,Week 12,5,2025-07-05,2025-07-12,Completed

In [84]:
visits.columns

Index(['visit_id', 'patient_id', 'trial_id', 'site_id', 'visit_name',
       'visit_sequence', 'scheduled_visit_date', 'actual_visit_date',
       'visit_status'],
      dtype='str')

In [85]:
visits.shape

(1525, 9)

In [86]:
visits.info()
visits.isnull().sum()
visits.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1525 entries, 0 to 1524
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   visit_id              1525 non-null   str
 1   patient_id            1525 non-null   str
 2   trial_id              1525 non-null   str
 3   site_id               1525 non-null   str
 4   visit_name            1525 non-null   str
 5   visit_sequence        1525 non-null   int64
 6   scheduled_visit_date  1525 non-null   str
 7   actual_visit_date     1289 non-null   str
 8   visit_status          1525 non-null   str
dtypes: int64(1), str(8)
memory usage: 205.8 KB

np.int64(0)

In [87]:
visits.dtypes

visit_id                  str
patient_id                str
trial_id                  str
site_id                   str
visit_name                str
visit_sequence          int64
scheduled_visit_date      str
actual_visit_date         str
visit_status              str
dtype: object

In [88]:
visits["visit_name"].value_counts() #to check the unique values in the visit_name column and their counts

visit_name
Screening        254
Baseline         254
Week 4           254
Week 8           254
Week 12          254
Week 24          254
Invalid Visit      1
Name: count, dtype: int64

In [89]:
adverse_events.head()

,ae_id,patient_id,trial_id,site_id,ae_term,severity,serious_flag,related_to_study_drug,reported_timestamp,ae_status
0,AE000001,P00245,CT-NEUR-004,SITE-017,Fatigue,Moderate,N,Y,2025-05-10 00:00:00,Open
1,AE000002,P00009,CT-ONC-001,SITE-001,Vomiting,Mild,N,N,2026-01-25 00:00:00,Closed
2,AE000003,P00009,CT-ONC-001,SITE-001,Fever,Severe,N,Y,2026-01-19 00:00:00,Open
3,AE000004,P00099,CT-CARD-002,SITE-007,Anemia,Severe,N,N,2025-08-14 00:00:00,Open
4,AE000005,P00099,CT-CARD-002,SITE-007,Dizziness,Mild,N,N,2025-10-25 00:00:00,Closed

In [90]:
adverse_events.shape

(380, 10)

In [91]:
adverse_events.dtypes

ae_id                    str
patient_id               str
trial_id                 str
site_id                  str
ae_term                  str
severity                 str
serious_flag             str
related_to_study_drug    str
reported_timestamp       str
ae_status                str
dtype: object

In [92]:
adverse_events.isnull().sum()

ae_id                    0
patient_id               0
trial_id                 0
site_id                  0
ae_term                  0
severity                 0
serious_flag             1
related_to_study_drug    0
reported_timestamp       0
ae_status                0
dtype: int64

In [93]:
adverse_events["serious_flag"].value_counts()

serious_flag
N    304
Y     75
Name: count, dtype: int64

In [94]:
protocol_deviations.head()

,deviation_id,patient_id,trial_id,site_id,visit_id,deviation_type,deviation_severity,deviation_date,deviation_status
0,PD000001,P00040,CT-ONC-001,SITE-004,V000196,Lab Sample Missing,Critical,2025-10-21,Open
1,PD000002,P00242,CT-NEUR-004,SITE-016,V001123,Missed Procedure,Major,2025-08-27,Closed
2,PD000003,P00052,CT-ONC-001,SITE-005,V000247,Lab Sample Missing,Minor,2025-05-28,Closed
3,PD000004,P00313,CT-NEUR-004,SITE-020,V001496,Informed Consent Issue,Minor,2026-01-08,Closed
4,PD000005,P00128,CT-CARD-002,SITE-009,V000611,Lab Sample Missing,Critical,2025-10-22,Open

In [95]:
protocol_deviations.isnull().sum()

deviation_id          0
patient_id            0
trial_id              0
site_id               0
visit_id              0
deviation_type        0
deviation_severity    0
deviation_date        0
deviation_status      0
dtype: int64

In [96]:
protocol_deviations["deviation_type"].value_counts() #to check the unique values in the deviation_type column and their counts

deviation_type
Visit Window Violation    12
Lab Sample Missing        11
Informed Consent Issue    10
Eligibility Deviation      7
Missed Procedure           4
Name: count, dtype: int64

In [97]:
protocol_deviations["trial_id"].value_counts() #to check the unique values in the trial_id column and their counts

trial_id
CT-CARD-002    13
CT-NEUR-004    11
CT-ONC-001     10
CT-DIAB-003    10
Name: count, dtype: int64

In [98]:
drug_inventory.head()

,inventory_id,trial_id,site_id,drug_name,batch_number,quantity_available,expiry_date,inventory_snapshot_date
0,INV000001,CT-ONC-001,SITE-001,Drug A,BATCH-9570,175,2026-04-09,2026-01-15
1,INV000002,CT-ONC-001,SITE-001,Drug A,BATCH-5991,14,2026-03-12,2026-01-15
2,INV000003,CT-ONC-001,SITE-001,Drug A,BATCH-4643,65,2026-03-24,2026-01-15
3,INV000004,CT-ONC-001,SITE-002,Drug A,BATCH-4712,157,2026-03-16,2026-01-15
4,INV000005,CT-ONC-001,SITE-002,Drug A,BATCH-4438,66,2026-02-20,2026-01-15

In [99]:
drug_inventory.isnull().sum()

inventory_id               0
trial_id                   0
site_id                    0
drug_name                  0
batch_number               0
quantity_available         0
expiry_date                0
inventory_snapshot_date    0
dtype: int64

In [100]:
drug_shipments.head()

,shipment_id,trial_id,site_id,drug_name,batch_number,quantity_shipped,shipment_sent_date,shipment_received_date,shipment_status
0,SHIP000001,CT-ONC-001,SITE-001,Drug A,BATCH-9686,148,2025-01-07,2025-01-10,Delayed
1,SHIP000002,CT-ONC-001,SITE-001,Drug A,BATCH-9842,359,2025-02-12,2025-02-26,Received
2,SHIP000003,CT-ONC-001,SITE-001,Drug A,BATCH-4409,241,2025-03-15,2025-03-29,Received
3,SHIP000004,CT-ONC-001,SITE-001,Drug A,BATCH-3444,450,2025-04-07,2025-04-10,Received
4,SHIP000005,CT-ONC-001,SITE-001,Drug A,BATCH-3617,443,2025-05-16,2025-05-20,Received

In [101]:
drug_shipments.isnull().sum()

shipment_id               0
trial_id                  0
site_id                   0
drug_name                 0
batch_number              0
quantity_shipped          0
shipment_sent_date        0
shipment_received_date    0
shipment_status           0
dtype: int64

In [102]:
drug_shipments["shipment_status"].value_counts() #to check the unique values in the shipment_status column and their counts

shipment_status
Received    91
Delayed     29
Name: count, dtype: int64

In [103]:
lab_results.head()

,lab_result_id,patient_id,trial_id,site_id,visit_id,test_name,result_value,unit,normal_low,normal_high,result_flag,collection_date
0,LAB000001,P00066,CT-ONC-001,SITE-005,V000309,Platelets,529.98,10^9/L,150.0,450.0,Abnormal,2025-07-19
1,LAB000002,P00066,CT-ONC-001,SITE-005,V000309,Creatinine,1.18,mg/dL,0.6,1.3,Normal,2025-07-19
2,LAB000003,P00280,CT-NEUR-004,SITE-018,V001336,Hemoglobin,25.03,g/dL,10.0,18.0,Abnormal,2025-09-07
3,LAB000004,P00280,CT-NEUR-004,SITE-018,V001336,Creatinine,1.65,mg/dL,0.6,1.3,Abnormal,2025-09-07
4,LAB000005,P00028,CT-ONC-001,SITE-003,V000143,Hemoglobin,15.19,g/dL,10.0,18.0,Normal,2025-09-19

In [104]:
lab_results.isnull().sum()

lab_result_id      0
patient_id         0
trial_id           0
site_id            0
visit_id           0
test_name          0
result_value       0
unit               0
normal_low         0
normal_high        0
result_flag        0
collection_date    0
dtype: int64

In [105]:
reference_codes.head()

      code_type code_value        code_description
0   AE_SEVERITY       Mild      Mild adverse event
1   AE_SEVERITY   Moderate  Moderate adverse event
2   AE_SEVERITY     Severe    Severe adverse event
3  VISIT_STATUS  Completed         Visit completed
4  VISIT_STATUS     Missed            Visit missed

In [106]:
reference_codes.isnull().sum()

code_type           0
code_value          0
code_description    0
dtype: int64

In [107]:
#to avoide repeating the same code for each dataframe we can create a function to profile the dataset(Resuable profiling function)

def profile_dataset(df, name):

    print(f"\n========== {name} ==========")

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nNull Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nSample Data:")
    print(df.head())

In [108]:
profile_dataset(trials,"Trials")

========== Trials ==========

Shape:
(4, 10)

Columns:
['trial_id', 'phase', 'therapeutic_area', 'sponsor', 'study_drug', 'indication', 'start_date', 'planned_end_date', 'trial_status', 'target_enrollment']

Data Types:
trial_id               str
phase                  str
therapeutic_area       str
sponsor                str
study_drug             str
indication             str
start_date             str
planned_end_date       str
trial_status           str
target_enrollment    int64
dtype: object

Null Values:
trial_id             0
phase                0
therapeutic_area     0
sponsor              0
study_drug           0
indication           0
start_date           0
planned_end_date     0
trial_status         0
target_enrollment    0
dtype: int64

Duplicate Rows:
0

Sample Data:
      trial_id    phase therapeutic_area          sponsor study_drug  \
0   CT-ONC-001  Phase 2         Oncology  NovaCure Pharma     Drug A
1  CT-CARD-002  Phase 3       Cardiology    MediCore Labs     Drug B
2  CT-DIAB-003  Phase 2    Endocrinology    HealthGen Bio     Drug C
3  CT-NEUR-004  Phase 1        Neurology        NeuroNova     Drug D

        indication  start_date planned_end_date trial_status  \
0    Breast Cancer  2025-01-15       2026-06-30       Active
1    Heart Failure  2025-03-01       2026-12-15       Active
2  Type 2 Diabetes  2024-11-20       2026-04-30       Active
3         Migraine  2025-06-10       2026-08-31   Recruiting

   target_enrollment
0                300
1                500
2                250
3                120

In [109]:
profile_dataset(patients, "Patients")

========== Patients ==========

Shape:
(318, 8)

Columns:
['patient_id', 'trial_id', 'site_id', 'gender', 'age', 'consent_date', 'treatment_arm', 'enrollment_status']

Data Types:
patient_id             str
trial_id               str
site_id                str
gender                 str
age                  int64
consent_date           str
treatment_arm          str
enrollment_status      str
dtype: object

Null Values:
patient_id           0
trial_id             1
site_id              0
gender               0
age                  0
consent_date         0
treatment_arm        0
enrollment_status    0
dtype: int64

Duplicate Rows:
0

Sample Data:
  patient_id    trial_id   site_id  gender  age consent_date treatment_arm  \
0     P00001  CT-ONC-001  SITE-001    Male   60   2025-04-12        Drug A
1     P00002  CT-ONC-001  SITE-001    Male   52   2025-07-06       Placebo
2     P00003  CT-ONC-001  SITE-001  Female   35   2025-02-18       Placebo
3     P00004  CT-ONC-001  SITE-001    Male   32   2025-07-02       Placebo
4     P00005  CT-ONC-001  SITE-001  Female   35   2025-08-02       Placebo

  enrollment_status
0          Enrolled
1          Enrolled
2     Screen Failed
3          Enrolled
4          Enrolled

In [110]:
profile_dataset(sites, "Sites")

========== Sites ==========

Shape:
(20, 8)

Columns:
['site_id', 'trial_id', 'site_name', 'country', 'country_code', 'principal_investigator', 'activation_date', 'site_status']

Data Types:
site_id                   str
trial_id                  str
site_name                 str
country                   str
country_code              str
principal_investigator    str
activation_date           str
site_status               str
dtype: object

Null Values:
site_id                   0
trial_id                  0
site_name                 0
country                   0
country_code              0
principal_investigator    0
activation_date           0
site_status               0
dtype: int64

Duplicate Rows:
0

Sample Data:
    site_id    trial_id   site_name        country country_code  \
0  SITE-001  CT-ONC-001  Hospital 1          India          IND
1  SITE-002  CT-ONC-001  Hospital 2  United States          USA
2  SITE-003  CT-ONC-001  Hospital 3          India          IND
3  SITE-004  CT-ONC-001  Hospital 4         Canada          CAN
4  SITE-005  CT-ONC-001  Hospital 5          India          IND

  principal_investigator activation_date site_status
0         Investigator 1      2025-01-07     Pending
1         Investigator 2      2025-02-27   Activated
2         Investigator 3      2025-06-23   Activated
3         Investigator 4      2025-04-19   Activated
4         Investigator 5      2025-01-24   Activated

In [111]:
profile_dataset(visits, "Visits")

========== Visits ==========

Shape:
(1525, 9)

Columns:
['visit_id', 'patient_id', 'trial_id', 'site_id', 'visit_name', 'visit_sequence', 'scheduled_visit_date', 'actual_visit_date', 'visit_status']

Data Types:
visit_id                  str
patient_id                str
trial_id                  str
site_id                   str
visit_name                str
visit_sequence          int64
scheduled_visit_date      str
actual_visit_date         str
visit_status              str
dtype: object

Null Values:
visit_id                  0
patient_id                0
trial_id                  0
site_id                   0
visit_name                0
visit_sequence            0
scheduled_visit_date      0
actual_visit_date       236
visit_status              0
dtype: int64

Duplicate Rows:
0

Sample Data:
  visit_id patient_id    trial_id   site_id visit_name  visit_sequence  \
0  V000001     P00001  CT-ONC-001  SITE-001  Screening               1
1  V000002     P00001  CT-ONC-001  SITE-001   Baseline               2
2  V000003     P00001  CT-ONC-001  SITE-001     Week 4               3
3  V000004     P00001  CT-ONC-001  SITE-001     Week 8               4
4  V000005     P00001  CT-ONC-001  SITE-001    Week 12               5

  scheduled_visit_date actual_visit_date visit_status
0           2025-04-12               NaN       Missed
1           2025-04-19        2025-04-17    Completed
2           2025-05-10        2025-05-13    Completed
3           2025-06-07        2025-06-09    Completed
4           2025-07-05        2025-07-12    Completed

In [112]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("data/raw")

def load_trials():
    return pd.read_csv(DATA_PATH / "trials.csv")

def load_patients():
    return pd.read_csv(DATA_PATH / "patients.csv")

def load_sites():
    return pd.read_csv(DATA_PATH / "sites.csv")

In [113]:
pd.head()

AttributeError: module 'pandas' has no attribute 'head'

# Dataset Relationships

## trials → patients
Connected using: trial_id

One trial can have many patients.

---

## trials → sites
Connected using: trial_id

One trial can run across multiple sites.

---

## patients → visits
Connected using: patient_id

One patient can have multiple visits.

---

## patients → adverse_events
Connected using: patient_id

One patient can report multiple adverse events.

---

## patients → protocol_deviations
Connected using: patient_id

One patient can have multiple protocol deviations.

---

## sites → drug_inventory
Connected using: site_id

Each site maintains drug inventory records.

---

## sites → drug_shipments
Connected using: site_id

Drug shipments are sent to sites.

---

## visits → lab_results
Connected using: visit_id

Lab results are recorded during patient visits.

# Week 1 Exploration Summary

## Completed Tasks

- Environment setup completed
- Virtual environment configured
- Project folder structure created
- Clinical trial datasets organized into data/raw
- All datasets loaded successfully using Pandas
- Dataset profiling completed for all CSV files
- Checked:
  - shape
  - columns
  - datatypes
  - null values
  - duplicate rows
  - categorical distributions
- Understood dataset relationships and schema structure
- Identified primary keys and foreign keys
- Identified initial data quality validation rules